#!/bin/python

import sys


t = int(raw_input().strip())


def checkAngry(k , a):
    length = len(a)
    studentsattended = 0
    for i in range(0,length):
        if (a[i]<=0):
            studentsattended = studentsattended+1
    if (studentsattended >= k):
        print "NO"
    else:
        print "YES"


for a0 in xrange(t):
    n,k = raw_input().strip().split(' ')
    n,k = [int(n),int(k)]
    a = map(int,raw_input().strip().split(' '))
    checkAngry(k, a)

