#!/bin/python

import sys

t = int(raw_input().strip())

def checkchanges(pointerlist):
    length = len(pointerlist)

    goodnode = list()
    badpointer =list()
    goodnode.append(1)
    output =0
    for i in range(1,length):
        if pointerlist[i] in goodnode:
            goodnode.append(i+1)
        else:
            if not pointerlist[i] in badpointer:
                badpointer.append(pointerlist[i])
                output=output+1
            else:
                pass
    #print goodnode
    return output

pointerlist = list()
for a0 in xrange(t):
    pointer = int(raw_input().strip())
    pointerlist.append(pointer)



output = checkchanges(pointerlist)
print output
